# GitLab CI/CD Pipeline for Deploying with rsync

# このパイプラインで使用するステージを定義
stages:
  - build
  - deploy

# ビルドジョブ
build_job:
  stage: build
  image: node:latest # プロジェクトに合わせて適切なNode.jsイメージを選択してください
  script:
    - npm install # または yarn install
    - npm run build && npm run export # ビルドと静的エクスポートコマンドに合わせて修正してください (例: next build && next export)
  artifacts:
    paths:
      - out/ # ビルド成果物ディレクトリを out/ に修正
    expire_in: 1 week
  only:
    - main # デプロイをトリガーするブランチ名に合わせて修正してください
    - master # 必要に応じて他のブランチやタグを追加

# デプロイジョブ
deploy_job:
  stage: deploy
  image: alpine:latest # rsyncとsshコマンドが使える軽量イメージ
  dependencies:
    - build_job # ビルドジョブの成果物に依存
  script:
    # rsyncコマンドでデプロイ
    # -z: 圧縮転送, -a: アーカイブモード (パーミッションなどを維持), -v: 詳細表示, --delete: 転送元にないファイルを転送先から削除
    - rsync -zav --delete out/ ubuntu:/var/www/youkan.uk/
      # ^^^ # ビルド成果物ディレクトリのパスを out/ に修正
      #     ^^^^^^^^^^^ # デプロイ先のサーバーユーザーとホスト名を直接指定 (必要に応じて環境変数に戻してください)
      #                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ # デプロイ先のパス
  only:
    - main # デプロイをトリガーするブランチ名に合わせて修正してください
    - master # 必要に応じて他のブランチやタグを追加 